### ISSUE TITLE
Version Updates of MlFlow

### ISSUE THREAD

**Issue by ElGarno** [aws-samples/sagemaker-studio-mlflow-integration#15]
First of all thank you very much!
Followed the instructions and it worked. The only thing I had to add was 
`pip install boto3`
before running 
`python add_users_and_groups.py`
The question now is: How would I proceed if I wanted to update **mlflow to version 2.8.0**?
I think I would also need a new **cognito-mlflow-patch** right?
Will there be a new release in the futre or is this setup limited to 2.5.0?

**Comment by pdifranc** [comment]
Hi @ElGarno 
happy to see you find this sample useful.
indeed, for every new version of `mlflow`, you would need a new patch for the MLflow UI. Usually the patches cannot be applied on newer versions out of the box, not because of the code changes (they are very small and trivial in the end), but mainly for conflicts with the `yarn.lock`. Every few months I do this exercise and update the repo to the latest stable MLflow, but right now I havent planned it yet. Likely will do this before the end of the year, but by then likely there is the possibility that mlflow will have released a newer version than `2.8.0`

**Comment by ElGarno** [comment]
Thanks for the fast response!
That was what I was hoping for so that this solution will be maintained for some time. 
Is it also possible, to generate this patch on my own so by a script or something? Looks as if multiple dependencies are updated there.

**Comment by pdifranc** [comment]
@ElGarno 
I just upgrade the patch to include MLflow `2.8.0`.
In general, when having conflicts on the `yarn.lock`, the easiet is to accept the changes from upstream, and then re-run `yarn install` to regenerate a new `yarn.lock` and include it in the patch.

Have fun!

**Comment by ElGarno** [comment]
@pdifranc Wow! Just amazing. Thx for updating so fast. I will have a look at it tomorrow.
Also thanks for the description.
Have a nice evening! 👍

**Comment by pdifranc** [comment]
@ElGarno - I realized that mlflow has released some experimental features released in recent versions of mlflow, e.g. Gateway AI, Prompt Engineering, and more that wont work out of the box with the current deployment.
I am working on extending this solution to also include the Gateway AI server to the deployment, so it works in tandem with the mlflow UI and mlflow tracking server using the same authentication mechanisms 🤟. While the deployment part works fine, I still need to update the labs to extend the sample.
Hope it is of interest

**Comment by ElGarno** [comment]
@pdifranc - For now I don't need these features but maybe some others are interested and for features like prompt engineering gain more and more importance.
So I am fine with the current status and more than happy with your great support!
So thanks again for your information and contribution and have a nice evening!
